//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPark.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=b1feb347-a856-4e2a-9223-a9a7010c7b61.sqlserver.sequelizer.com;Initial" +
            " Catalog=dbb1feb347a8564e2a9223a9a7010c7b61;Persist Security Info=True;User ID=e" +
            "wvceiluattpbfqh;Password=34wKA4rydVBiVZRFhmXf3MuJ5dycnM4YSK8sYpdqJzbx2sbhcpBZwEx" +
            "pGVNxCpkx")]
        public string ConnString {
            get {
                return ((string)(this["ConnString"]));
            }
        }
    }
}
